// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      name: 'Prineth Fernando',
      img: 'https://avatars.githubusercontent.com/u/70090385?v=4',
      github: 'https://github.com/prineth',
      linkedin: 'https://linkedin.com/in/prineth-fernando',
    },
    {
      name: 'Muhammad Uzair',
      img: 'https://avatars.githubusercontent.com/u/89875366?v=4',
      github: 'https://github.com/heyitsuzair',
      linkedin: 'https://linkedin.com/in/uzair-dev',
    },
    {
      name: 'Teddy Firman',
      img: 'https://avatars.githubusercontent.com/u/44187690?s=400&u=5697ad3a5b29e193d306985aafea565d01223e41&v=4',
      github: 'https://github.com/TeddyFirman',
      linkedin: 'www.linkedin.com/in/teddyfirman',
    },
    {
      name: 'Shamil Keheliya',
      img: 'https://avatars.githubusercontent.com/u/62515133?v=4',
      github: 'https://github.com/shamilkeheliya',
      linkedin: 'https://linkedin.com/in/shamilkeheliya',
    },
    {
      name: 'Deepak',
      img: 'https://avatars.githubusercontent.com/u/60574055?v=4',
      github: 'https://github.com/darakhshadeepak',
      linkedin: 'https://www.linkedin.com/in/deepak-gautam-14b027184/',
    },
    {
      name: 'Ugur Atmaca',
      img: 'https://avatars.githubusercontent.com/u/1944295?v=4',
      github: 'https://github.com/uguratmaca',
      linkedin: 'https://www.linkedin.com/in/atmacaugur/',
    },
    {
      name: 'Ankit Goyal',
      img: 'https://avatars.githubusercontent.com/u/91560072?v=4',
      github: 'https://github.com/Ankit9126',
      linkedin: 'https://www.linkedin.com/in/ankit-goyal-3416b9228/',
    },
    {
      name: 'Jai Patel',
      img: 'https://avatars.dicebear.com/api/open-peeps/jaipatel.png',
      github: 'https://github.com/goldenPheonix02',
      linkedin: 'https://www.linkedin.com/in/jai-patel-605900202/',
    },
    {
      name: 'Mihin Nimnaka',
      img: 'https://avatars.githubusercontent.com/u/39882449?v=4',
      github: 'https://github.com/mihinN',
      linkedin: 'www.linkedin.com/in/mihin-nimnaka',
    },
    {
      name: 'Muhammad Sabili Nurilhaq',
      img: 'https://avatars.githubusercontent.com/u/73186952?v=4',
      github: 'https://github.com/abilsabili50',
      linkedin: 'https://www.linkedin.com/in/abilsabili50/',
    },
    {
      name: 'Yusril Adriansyah Putra',
      img: 'https://avatars.githubusercontent.com/u/59789707?v=4',
      github: 'https://github.com/yusril-adr',
      linkedin: 'https://www.linkedin.com/in/yusril-adr',
    },
    {
      name: 'Moch. Faisal Khoiruidn',
      img: 'https://avatars.githubusercontent.com/u/39431576?v=4',
      github: 'https://github.com/putrasena21',
      linkedin: 'https://www.linkedin.com/in/moch-faisal-khoirudin/',
    },
    {
      name: 'Mochamad Muzayyid Al Hakim',
      img: 'https://avatars.githubusercontent.com/u/58965738?v=4',
      github: 'https://github.com/zayyid123',
      linkedin: 'https://www.linkedin.com/in/mochamad-zayyid-09178518b/',
    },
    {
      name: 'Sai Kiranman Singh',
      img: 'https://avatars.githubusercontent.com/u/78642772?v=4',
      github: 'https://github.com/skms625',
      linkedin: 'https://www.linkedin.com/in/sai-kiranman-singh-406959210/',
    },
    {
      name: 'Osamudiame Ruth Igbinoba',
      img: 'https://avatars.githubusercontent.com/u/65790714?v=4',
      github: 'https://github.com/Mudi-Igbinoba',
      linkedin: 'https://www.linkedin.com/in/osamudiame-igbinoba/',
    },
    {
      name: 'Mochamad Sofyan',
      img: 'https://avatars.githubusercontent.com/u/58968418?v=4',
      github: 'https://github.com/sofyanmoch',
      linkedin: 'https://www.linkedin.com/in/sofyanmoch/',
    },
    {
      name: 'SP KariSims',
      img: 'https://avatars.githubusercontent.com/u/79909649?s=96&v=4',
      github: 'https://github.com/KariSims',
      linkedin: 'https://www.linkedin.com/in/ameliefournier',
    },
    {
      name: 'Al Seny DIALLO',
      img: 'https://avatars.githubusercontent.com/u/68450529?v=4',
      github: 'https://github.com/alseny-diallo',
      linkedin: 'https://www.linkedin.com/in/alseny-diallo-5a2aa01b5/',
    },
    {
      name: 'Bhautik Poshiya',
      img: 'https://avatars.githubusercontent.com/u/79909649?s=96&v=4',
      github: 'https://github.com/bhautikposhiya',
      linkedin: 'https://www.linkedin.com/in/bhautik-poshiya',
    },
    {
      name: 'Muhammad Immad',
      img: 'https://avatars.githubusercontent.com/u/115941738?v=4',
      github: 'https://github.com/itsimmad',
      linkedin: 'https://www.linkedin.com/in/muhammad-immad-7b4553207',
    },
    {
      name: 'Nashir Resta Fauzian',
      img: 'https://avatars.githubusercontent.com/u/91722193?v=4',
      github: 'https://github.com/justRizu',
      linkedin: 'https://www.linkedin.com/in/nashir-resta-200ba224b/',
    },
    {
      name: 'avlindork',
      img: 'https://avatars.githubusercontent.com/u/72280160?v=4',
      github: '',
      linkedin: '',
    },
    {
      name: 'Adeeshya Ekanayake',
      img: 'https://avatars.githubusercontent.com/u/71784535?s=400&u=2d89bd2f0d9a702f53fba120013b65d005a390c7&v=4',
      github: 'https://github.com/Adeeshya',
      linkedin: 'https://www.linkedin.com/in/adeeshya-ekanayake-8483651bb/',
    },
    {
      name: 'Hari Sankar',
      img: 'https://avatars.githubusercontent.com/u/72344536?s=96&v=4',
      github: 'https://github.com/h4r1337',
      linkedin: 'https://www.linkedin.com/in/hari-sankar-rs-4bb222203/',
    },

    {
      name: 'Ankit Yadav',
      img: 'https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/10/Naruto-Every-Movie-In-Order-Of-Release.png?q=50&fit=contain&w=750&h=&dpr=1.5',
      github: 'https://github.com/ankitcr7-afk',
      linkedin: 'https://www.linkedin.com/in/ankit-yadav-7190761bb/',
    },
    {
      name: 'Lifan Dwinur Andrianto',
      img: 'https://avatars.githubusercontent.com/u/85450625?v=4',
      github: 'https://github.com/lifanandriand',
      linkedin: 'https://www.linkedin.com/in/lifandwinur/',
    },
    {
      name: 'Mohd Zaid',
      img: 'https://media-exp1.licdn.com/dms/image/C4D03AQFspq8O1ZHLaQ/profile-displayphoto-shrink_800_800/0/1611066866880?e=1671667200&v=beta&t=QRh7hGEnOfSfGoivoTtT_O-tfoe9om7R497rV0qRj_k',
      github: 'https://github.com/Xaid-vfx',
      linkedin: 'https://www.linkedin.com/in/mohd-zaid-3889801b7',
    },
    {
      name: 'Jayath De Silva',
      img: 'https://avatars.githubusercontent.com/u/92852913?v=4',
      github: 'https://github.com/JayathJSD',
      linkedin: 'https://www.linkedin.com/in/jayath-de-silva-jay/',
    },
    {
      name: 'Prishith Fernando',
      img: 'https://avatars.githubusercontent.com/u/116113828?v=4',
      github: 'https://github.com/prishithfernando',
      linkedin: '',
    },
    {
      name: 'Wildan Rozaqi',
      img: 'https://avatars.githubusercontent.com/u/44537983?s=400&u=0479c422dc68db4f6d3197361cde924e1f4b625b&v=4',
      github: 'https://github.com/WildanR19',
      linkedin: 'https://www.linkedin.com/in/wildan-rozaqi-575806204/',
    },
    {
      name: 'Sunali Rambukwella',
      img: 'https://avatars.githubusercontent.com/u/44220456?v=4',
      github: 'https://github.com/sunalii',
      linkedin: 'https://linkedin.com/in/sunali-rambukwella',
    },
    {
      name: 'Mohak SInghania',
      img: 'https://avatars.githubusercontent.com/u/112251355?v=4',
      github: 'https://github.com/MohakSinghania',
      linkedin: 'https://www.linkedin.com/in/mohak-singhania-9a1160215/',
    },
    {
      name: 'Shreyansh Goyal',
      img: 'https://i.ibb.co/n7SJdVb/1641913765443.jpg',
      github: 'https://github.com/101noobcoder101',
      linkedin: 'https://www.linkedin.com/in/shreyansh-goyal-9b79b8229/',
    },
    {
      name: 'Nilesh Ashok Ghone',
      img: 'https://avatars.githubusercontent.com/u/33826370?v=4',
      github: 'https://github.com/Nilesh-Ghone',
      linkedin: 'https://in.linkedin.com/in/nilesh-ghone-20746013',
    },
    {
      name: 'Atharv Phadnis',
      img: 'https://avatars.githubusercontent.com/u/31766648?v=4',
      github: 'https://github.com/Athi223',
      linkedin: 'https://www.linkedin.com/in/atharv-phadnis',
    },
    {
      name: 'Greggy Gianini Firmansyah',
      img: 'https://avatars.githubusercontent.com/u/34617290?v=4',
      github: 'https://github.com/greggygf',
      linkedin: 'https://www.linkedin.com/in/greggygf/',
    },
    {
      name: 'Lata',
      img: 'https://avatars.githubusercontent.com/u/103296906?v=4',
      github: 'https://github.com/lata-11',
      linkedin: 'https://www.linkedin.com/in/lata-800988222',
    },
    {
      name: 'Shubham Goyal',
      img: 'https://avatars.githubusercontent.com/u/85388284?v=4',
      github: 'https://github.com/ShubhamGoyal7125',
      linkedin: 'https://www.linkedin.com/in/shubham-goyal-7987461b8/',
    },
    {
      name: 'Chethana',
      img: 'https://avatars.githubusercontent.com/u/71955126?s=400&u=c58e81790a5153a62fe632b4768f37c29107d07b&v=4',
      github: 'https://github.com/dhavaji',
      linkedin: 'www.linkedin.com/in/chethana-wickrama-arachchi',
    },
    {
      name: 'EMMANUEL DIATTA',
      img: 'https://avatars.githubusercontent.com/u/80013080?v=4',
      github: 'https://github.com/Lowkey-Emmanuel',
      linkedin: 'https://www.linkedin.com/in/emmanuel-diatta-807462156/',
    },
    {
      name: 'Chathura',
      img: 'https://avatars.githubusercontent.com/u/61589293?v=4',
      github: 'https://github.com/PRO-GUNE',
      linkedin: 'www.linkedin.com/in/chathura-gunasekera-633561215',
    },
    {
      name: 'PhilipBDev',
      img: 'https://avatars.githubusercontent.com/u/26912166?v=4',
      github: 'https://github.com/PhilipBDev',
      linkedin: 'https://www.linkedin.com/in/philiprbrown/',
    },
     {
      name: 'Bimalka Nugapitiya',
      github: 'https://github.com/Bimi98',
    },
      {
      name: 'SHEHEER ALI',
      img: 'https://avatars.githubusercontent.com/u/67970285?v=4',
      github: 'https://github.com/SHEHEERALIZX',
      linkedin: 'https://www.linkedin.com/in/sheheeralizx/',
    },
    {
      name: 'Tapan Dabhi',
      img: 'https://avatars.githubusercontent.com/u/37927312?s=400&u=06270e19c6204ab3c0ecde8bd39f6aecd63fc04e&v=4',
      github: 'https://github.com/dabhitapan',
      linkedin: 'https://www.linkedin.com/in/tapan-dabhi/',
    },
    {
		"name": "Berika Şener",
		"gh_username": "berikasener",
		"place": "Turkiye",
		"current_pos": "Linux System Administrator",
		"image": null,
		"bio": "Trying to learn Linux and also a front-end developer."
	},
	  {
      name: 'Urmil Bhavsar',
      github: 'https://github.com/urmil22',
      linkedin: 'https://www.linkedin.com/in/urmil-bhavsar/',
    },
      {
      name: 'Arnav Agarwal',
      github: 'https://github.com/arnav0929',
      bio: 'learning backend development.'
    },
	{
      name: 'Parikshit Hiwase',
      img: 'https://avatars.githubusercontent.com/u/55256204?s=400&u=a4769706a829190dc94496a4d7dcc0604693d204&v=4',
      github: 'https://github.com/Parikshit001',
      linkedin: 'https://www.linkedin.com/in/parikshit-hiwase-a238b320b/',
    },
	  	{
      name: 'Rishabh Pandey',
      img: 'https://avatars.githubusercontent.com/u/72344536?s=96&v=4',
      github: 'https://github.com/rishabh-pandey-393',
    },
  ])
}
